// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/drive.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ConfigName           string   `protobuf:"bytes,2,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_5b335228c5116ae5, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Request) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

type Detail struct {
	IsEnd                string   `protobuf:"bytes,1,opt,name=is_end,json=isEnd,proto3" json:"is_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Detail) Reset()         { *m = Detail{} }
func (m *Detail) String() string { return proto.CompactTextString(m) }
func (*Detail) ProtoMessage()    {}
func (*Detail) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_5b335228c5116ae5, []int{1}
}
func (m *Detail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Detail.Unmarshal(m, b)
}
func (m *Detail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Detail.Marshal(b, m, deterministic)
}
func (dst *Detail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Detail.Merge(dst, src)
}
func (m *Detail) XXX_Size() int {
	return xxx_messageInfo_Detail.Size(m)
}
func (m *Detail) XXX_DiscardUnknown() {
	xxx_messageInfo_Detail.DiscardUnknown(m)
}

var xxx_messageInfo_Detail proto.InternalMessageInfo

func (m *Detail) GetIsEnd() string {
	if m != nil {
		return m.IsEnd
	}
	return ""
}

type List struct {
	Tags                 string   `protobuf:"bytes,1,opt,name=tags,proto3" json:"tags,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	ResourceName         string   `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceUrl          string   `protobuf:"bytes,4,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	ResourceImgUrl       string   `protobuf:"bytes,5,opt,name=resource_img_url,json=resourceImgUrl,proto3" json:"resource_img_url,omitempty"`
	Author               string   `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_5b335228c5116ae5, []int{2}
}
func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (dst *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(dst, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *List) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *List) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *List) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

func (m *List) GetResourceImgUrl() string {
	if m != nil {
		return m.ResourceImgUrl
	}
	return ""
}

func (m *List) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type ListReply struct {
	Data                 []*List  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Next                 string   `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReply) Reset()         { *m = ListReply{} }
func (m *ListReply) String() string { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()    {}
func (*ListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_5b335228c5116ae5, []int{3}
}
func (m *ListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReply.Unmarshal(m, b)
}
func (m *ListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReply.Marshal(b, m, deterministic)
}
func (dst *ListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReply.Merge(dst, src)
}
func (m *ListReply) XXX_Size() int {
	return xxx_messageInfo_ListReply.Size(m)
}
func (m *ListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListReply proto.InternalMessageInfo

func (m *ListReply) GetData() []*List {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListReply) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

type Chapter struct {
	IsFree               string   `protobuf:"bytes,1,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	ResourceName         string   `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceUrl          string   `protobuf:"bytes,3,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	ResourceImgUrl       string   `protobuf:"bytes,4,opt,name=resource_img_url,json=resourceImgUrl,proto3" json:"resource_img_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chapter) Reset()         { *m = Chapter{} }
func (m *Chapter) String() string { return proto.CompactTextString(m) }
func (*Chapter) ProtoMessage()    {}
func (*Chapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_5b335228c5116ae5, []int{4}
}
func (m *Chapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chapter.Unmarshal(m, b)
}
func (m *Chapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chapter.Marshal(b, m, deterministic)
}
func (dst *Chapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chapter.Merge(dst, src)
}
func (m *Chapter) XXX_Size() int {
	return xxx_messageInfo_Chapter.Size(m)
}
func (m *Chapter) XXX_DiscardUnknown() {
	xxx_messageInfo_Chapter.DiscardUnknown(m)
}

var xxx_messageInfo_Chapter proto.InternalMessageInfo

func (m *Chapter) GetIsFree() string {
	if m != nil {
		return m.IsFree
	}
	return ""
}

func (m *Chapter) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *Chapter) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

func (m *Chapter) GetResourceImgUrl() string {
	if m != nil {
		return m.ResourceImgUrl
	}
	return ""
}

type ChapterReply struct {
	Data                 []*Chapter `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Detail               *Detail    `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Next                 string     `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChapterReply) Reset()         { *m = ChapterReply{} }
func (m *ChapterReply) String() string { return proto.CompactTextString(m) }
func (*ChapterReply) ProtoMessage()    {}
func (*ChapterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_5b335228c5116ae5, []int{5}
}
func (m *ChapterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterReply.Unmarshal(m, b)
}
func (m *ChapterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterReply.Marshal(b, m, deterministic)
}
func (dst *ChapterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterReply.Merge(dst, src)
}
func (m *ChapterReply) XXX_Size() int {
	return xxx_messageInfo_ChapterReply.Size(m)
}
func (m *ChapterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterReply proto.InternalMessageInfo

func (m *ChapterReply) GetData() []*Chapter {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ChapterReply) GetDetail() *Detail {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (m *ChapterReply) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

type ChapterContent struct {
	ResourceImgUrl       []string `protobuf:"bytes,1,rep,name=resource_img_url,json=resourceImgUrl,proto3" json:"resource_img_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChapterContent) Reset()         { *m = ChapterContent{} }
func (m *ChapterContent) String() string { return proto.CompactTextString(m) }
func (*ChapterContent) ProtoMessage()    {}
func (*ChapterContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_5b335228c5116ae5, []int{6}
}
func (m *ChapterContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterContent.Unmarshal(m, b)
}
func (m *ChapterContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterContent.Marshal(b, m, deterministic)
}
func (dst *ChapterContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterContent.Merge(dst, src)
}
func (m *ChapterContent) XXX_Size() int {
	return xxx_messageInfo_ChapterContent.Size(m)
}
func (m *ChapterContent) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterContent.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterContent proto.InternalMessageInfo

func (m *ChapterContent) GetResourceImgUrl() []string {
	if m != nil {
		return m.ResourceImgUrl
	}
	return nil
}

type ChapterContentReply struct {
	Data                 []*ChapterContent `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Next                 string            `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChapterContentReply) Reset()         { *m = ChapterContentReply{} }
func (m *ChapterContentReply) String() string { return proto.CompactTextString(m) }
func (*ChapterContentReply) ProtoMessage()    {}
func (*ChapterContentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_5b335228c5116ae5, []int{7}
}
func (m *ChapterContentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterContentReply.Unmarshal(m, b)
}
func (m *ChapterContentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterContentReply.Marshal(b, m, deterministic)
}
func (dst *ChapterContentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterContentReply.Merge(dst, src)
}
func (m *ChapterContentReply) XXX_Size() int {
	return xxx_messageInfo_ChapterContentReply.Size(m)
}
func (m *ChapterContentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterContentReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterContentReply proto.InternalMessageInfo

func (m *ChapterContentReply) GetData() []*ChapterContent {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ChapterContentReply) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "grpc.Request")
	proto.RegisterType((*Detail)(nil), "grpc.Detail")
	proto.RegisterType((*List)(nil), "grpc.List")
	proto.RegisterType((*ListReply)(nil), "grpc.ListReply")
	proto.RegisterType((*Chapter)(nil), "grpc.Chapter")
	proto.RegisterType((*ChapterReply)(nil), "grpc.ChapterReply")
	proto.RegisterType((*ChapterContent)(nil), "grpc.ChapterContent")
	proto.RegisterType((*ChapterContentReply)(nil), "grpc.ChapterContentReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BrowserClient is the client API for Browser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrowserClient interface {
	CrawlList(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ListReply, error)
	CrawlChapter(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ChapterReply, error)
	CrawlChapterContent(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ChapterContentReply, error)
}

type browserClient struct {
	cc *grpc.ClientConn
}

func NewBrowserClient(cc *grpc.ClientConn) BrowserClient {
	return &browserClient{cc}
}

func (c *browserClient) CrawlList(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, "/grpc.browser/CrawlList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) CrawlChapter(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ChapterReply, error) {
	out := new(ChapterReply)
	err := c.cc.Invoke(ctx, "/grpc.browser/CrawlChapter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserClient) CrawlChapterContent(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ChapterContentReply, error) {
	out := new(ChapterContentReply)
	err := c.cc.Invoke(ctx, "/grpc.browser/CrawlChapterContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrowserServer is the server API for Browser service.
type BrowserServer interface {
	CrawlList(context.Context, *Request) (*ListReply, error)
	CrawlChapter(context.Context, *Request) (*ChapterReply, error)
	CrawlChapterContent(context.Context, *Request) (*ChapterContentReply, error)
}

func RegisterBrowserServer(s *grpc.Server, srv BrowserServer) {
	s.RegisterService(&_Browser_serviceDesc, srv)
}

func _Browser_CrawlList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).CrawlList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.browser/CrawlList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).CrawlList(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_CrawlChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).CrawlChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.browser/CrawlChapter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).CrawlChapter(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Browser_CrawlChapterContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServer).CrawlChapterContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.browser/CrawlChapterContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServer).CrawlChapterContent(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Browser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.browser",
	HandlerType: (*BrowserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrawlList",
			Handler:    _Browser_CrawlList_Handler,
		},
		{
			MethodName: "CrawlChapter",
			Handler:    _Browser_CrawlChapter_Handler,
		},
		{
			MethodName: "CrawlChapterContent",
			Handler:    _Browser_CrawlChapterContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/drive.proto",
}

func init() { proto.RegisterFile("grpc/drive.proto", fileDescriptor_drive_5b335228c5116ae5) }

var fileDescriptor_drive_5b335228c5116ae5 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcb, 0x6e, 0xd4, 0x40,
	0x10, 0xc4, 0xb1, 0x63, 0x6b, 0xdb, 0x4e, 0x58, 0x4d, 0x20, 0x18, 0x0e, 0x24, 0x31, 0x1c, 0x7c,
	0x61, 0x91, 0x36, 0x37, 0x84, 0x84, 0xd0, 0x02, 0x12, 0x12, 0xe2, 0xb0, 0x88, 0xb3, 0x35, 0x59,
	0x77, 0x9c, 0x11, 0x7e, 0x31, 0x33, 0x26, 0xf0, 0x1f, 0x7c, 0x08, 0x1f, 0xc0, 0xc7, 0xa1, 0x79,
	0xd8, 0x8a, 0x77, 0x8d, 0xb4, 0xb7, 0x99, 0xee, 0xaa, 0xe9, 0xaa, 0x2e, 0x1b, 0xe6, 0x05, 0x6f,
	0x37, 0x2f, 0x73, 0xce, 0x7e, 0xe0, 0xa2, 0xe5, 0x8d, 0x6c, 0x88, 0xa7, 0x2a, 0xc9, 0x6b, 0x08,
	0xd6, 0xf8, 0xbd, 0x43, 0x21, 0xc9, 0x1c, 0xdc, 0x8e, 0x97, 0xb1, 0x73, 0xee, 0xa4, 0xb3, 0xb5,
	0x3a, 0x92, 0x33, 0x08, 0x37, 0x4d, 0x7d, 0xcd, 0x8a, 0xac, 0xa6, 0x15, 0xc6, 0x07, 0xba, 0x03,
	0xa6, 0xf4, 0x99, 0x56, 0x98, 0x9c, 0x81, 0xff, 0x0e, 0x25, 0x65, 0x25, 0x79, 0x08, 0x3e, 0x13,
	0x19, 0xd6, 0xb9, 0xe5, 0x1f, 0x32, 0xf1, 0xbe, 0xce, 0x93, 0xbf, 0x0e, 0x78, 0x9f, 0x98, 0x90,
	0x84, 0x80, 0x27, 0x69, 0x21, 0x6c, 0x57, 0x9f, 0xc9, 0x29, 0xf8, 0xb9, 0x66, 0xdb, 0x97, 0xed,
	0x8d, 0x3c, 0x83, 0x23, 0x8e, 0xa2, 0xe9, 0xf8, 0x06, 0xcd, 0x60, 0x57, 0xb7, 0xa3, 0xbe, 0xa8,
	0x46, 0x93, 0x0b, 0x18, 0xee, 0x99, 0x92, 0xed, 0x69, 0x4c, 0xd8, 0xd7, 0xbe, 0xf2, 0x92, 0xa4,
	0x30, 0x1f, 0x20, 0xac, 0x2a, 0x34, 0xec, 0x50, 0xc3, 0x8e, 0xfb, 0xfa, 0xc7, 0xaa, 0x50, 0xc8,
	0x53, 0xf0, 0x69, 0x27, 0x6f, 0x1a, 0x1e, 0xfb, 0x46, 0x89, 0xb9, 0x25, 0x6f, 0x60, 0xa6, 0xd4,
	0xaf, 0xb1, 0x2d, 0x7f, 0x91, 0xa7, 0xe0, 0xe5, 0x54, 0xd2, 0xd8, 0x39, 0x77, 0xd3, 0x70, 0x09,
	0x0b, 0xb5, 0xbf, 0x85, 0x6e, 0xeb, 0xba, 0xb2, 0x58, 0xe3, 0x4f, 0x69, 0xcd, 0xe8, 0x73, 0xf2,
	0xdb, 0x81, 0x60, 0x75, 0x43, 0x5b, 0x89, 0x9c, 0x3c, 0x82, 0x80, 0x89, 0xec, 0x9a, 0x23, 0xda,
	0x2d, 0xf8, 0x4c, 0x7c, 0xe0, 0x88, 0xbb, 0x7e, 0x0f, 0xf6, 0xf0, 0xeb, 0xee, 0xe7, 0xd7, 0x9b,
	0xf2, 0x9b, 0x7c, 0x83, 0xc8, 0xaa, 0x32, 0xd6, 0x2e, 0x46, 0xd6, 0x8e, 0x8c, 0xb5, 0x1e, 0x61,
	0xdc, 0x3d, 0x1f, 0xc2, 0x52, 0x93, 0xc3, 0x65, 0x64, 0x40, 0x26, 0xfe, 0x21, 0xba, 0xa9, 0x1d,
	0xbc, 0x82, 0x63, 0xfb, 0xd4, 0xaa, 0xa9, 0x25, 0xd6, 0x72, 0x52, 0xa8, 0x1a, 0xbd, 0x2b, 0xf4,
	0x0b, 0x9c, 0x8c, 0xb9, 0x46, 0x6f, 0x3a, 0xd2, 0xfb, 0x60, 0xa4, 0xb7, 0x07, 0xfe, 0x37, 0x94,
	0xe5, 0x1f, 0x07, 0x82, 0x2b, 0xde, 0xdc, 0x0a, 0xe4, 0xe4, 0x05, 0xcc, 0x56, 0x9c, 0xde, 0x96,
	0xfa, 0x23, 0xb5, 0xc6, 0xed, 0x0f, 0xf1, 0xe4, 0xfe, 0x9d, 0x88, 0xd5, 0xd8, 0xe4, 0x1e, 0xb9,
	0x84, 0x48, 0xc3, 0xfb, 0x4c, 0xb7, 0x18, 0x64, 0xbc, 0x39, 0x4b, 0x7a, 0x0b, 0x27, 0x77, 0x49,
	0xfd, 0x16, 0xb6, 0xb8, 0x8f, 0x27, 0x5d, 0x98, 0x27, 0xae, 0x7c, 0xfd, 0xcf, 0x5e, 0xfe, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x50, 0xeb, 0x81, 0x5b, 0xc7, 0x03, 0x00, 0x00,
}
