// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/drive.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ConfigName           string   `protobuf:"bytes,2,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_bb4c53071af39e65, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Request) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Request) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

type Book struct {
	Tags                 string   `protobuf:"bytes,1,opt,name=tags,proto3" json:"tags,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	ResourceName         string   `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceUrl          string   `protobuf:"bytes,4,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	ResourceImgUrl       string   `protobuf:"bytes,5,opt,name=resource_img_url,json=resourceImgUrl,proto3" json:"resource_img_url,omitempty"`
	Author               string   `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_bb4c53071af39e65, []int{1}
}
func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (dst *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(dst, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Book) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Book) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *Book) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

func (m *Book) GetResourceImgUrl() string {
	if m != nil {
		return m.ResourceImgUrl
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type Detail struct {
	Tags                 string   `protobuf:"bytes,1,opt,name=tags,proto3" json:"tags,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	IsEnd                string   `protobuf:"bytes,3,opt,name=is_end,json=isEnd,proto3" json:"is_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Detail) Reset()         { *m = Detail{} }
func (m *Detail) String() string { return proto.CompactTextString(m) }
func (*Detail) ProtoMessage()    {}
func (*Detail) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_bb4c53071af39e65, []int{2}
}
func (m *Detail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Detail.Unmarshal(m, b)
}
func (m *Detail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Detail.Marshal(b, m, deterministic)
}
func (dst *Detail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Detail.Merge(dst, src)
}
func (m *Detail) XXX_Size() int {
	return xxx_messageInfo_Detail.Size(m)
}
func (m *Detail) XXX_DiscardUnknown() {
	xxx_messageInfo_Detail.DiscardUnknown(m)
}

var xxx_messageInfo_Detail proto.InternalMessageInfo

func (m *Detail) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Detail) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Detail) GetIsEnd() string {
	if m != nil {
		return m.IsEnd
	}
	return ""
}

type Chapter struct {
	IsFree               string   `protobuf:"bytes,1,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	ResourceName         string   `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Detail               string   `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	ResourceUrl          string   `protobuf:"bytes,3,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	Sort                 string   `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty"`
	ResourceImgUrl       string   `protobuf:"bytes,4,opt,name=resource_img_url,json=resourceImgUrl,proto3" json:"resource_img_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chapter) Reset()         { *m = Chapter{} }
func (m *Chapter) String() string { return proto.CompactTextString(m) }
func (*Chapter) ProtoMessage()    {}
func (*Chapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_bb4c53071af39e65, []int{3}
}
func (m *Chapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chapter.Unmarshal(m, b)
}
func (m *Chapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chapter.Marshal(b, m, deterministic)
}
func (dst *Chapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chapter.Merge(dst, src)
}
func (m *Chapter) XXX_Size() int {
	return xxx_messageInfo_Chapter.Size(m)
}
func (m *Chapter) XXX_DiscardUnknown() {
	xxx_messageInfo_Chapter.DiscardUnknown(m)
}

var xxx_messageInfo_Chapter proto.InternalMessageInfo

func (m *Chapter) GetIsFree() string {
	if m != nil {
		return m.IsFree
	}
	return ""
}

func (m *Chapter) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *Chapter) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Chapter) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

func (m *Chapter) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *Chapter) GetResourceImgUrl() string {
	if m != nil {
		return m.ResourceImgUrl
	}
	return ""
}

type Content struct {
	ResourceImgUrl       string   `protobuf:"bytes,1,opt,name=resource_img_url,json=resourceImgUrl,proto3" json:"resource_img_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_bb4c53071af39e65, []int{4}
}
func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (dst *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(dst, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetResourceImgUrl() string {
	if m != nil {
		return m.ResourceImgUrl
	}
	return ""
}

type Res struct {
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []*Book  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Detail               *Detail  `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Next                 bool     `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Res) Reset()         { *m = Res{} }
func (m *Res) String() string { return proto.CompactTextString(m) }
func (*Res) ProtoMessage()    {}
func (*Res) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_bb4c53071af39e65, []int{5}
}
func (m *Res) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Res.Unmarshal(m, b)
}
func (m *Res) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Res.Marshal(b, m, deterministic)
}
func (dst *Res) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Res.Merge(dst, src)
}
func (m *Res) XXX_Size() int {
	return xxx_messageInfo_Res.Size(m)
}
func (m *Res) XXX_DiscardUnknown() {
	xxx_messageInfo_Res.DiscardUnknown(m)
}

var xxx_messageInfo_Res proto.InternalMessageInfo

func (m *Res) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Res) GetData() []*Book {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Res) GetDetail() *Detail {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (m *Res) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

type ResChapter struct {
	Id                   string     `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []*Chapter `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Detail               *Detail    `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Next                 bool       `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ResChapter) Reset()         { *m = ResChapter{} }
func (m *ResChapter) String() string { return proto.CompactTextString(m) }
func (*ResChapter) ProtoMessage()    {}
func (*ResChapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_bb4c53071af39e65, []int{6}
}
func (m *ResChapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResChapter.Unmarshal(m, b)
}
func (m *ResChapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResChapter.Marshal(b, m, deterministic)
}
func (dst *ResChapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResChapter.Merge(dst, src)
}
func (m *ResChapter) XXX_Size() int {
	return xxx_messageInfo_ResChapter.Size(m)
}
func (m *ResChapter) XXX_DiscardUnknown() {
	xxx_messageInfo_ResChapter.DiscardUnknown(m)
}

var xxx_messageInfo_ResChapter proto.InternalMessageInfo

func (m *ResChapter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResChapter) GetData() []*Chapter {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResChapter) GetDetail() *Detail {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (m *ResChapter) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

type ResContent struct {
	Id                   string     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []*Content `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Next                 bool       `protobuf:"varint,3,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ResContent) Reset()         { *m = ResContent{} }
func (m *ResContent) String() string { return proto.CompactTextString(m) }
func (*ResContent) ProtoMessage()    {}
func (*ResContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_drive_bb4c53071af39e65, []int{7}
}
func (m *ResContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResContent.Unmarshal(m, b)
}
func (m *ResContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResContent.Marshal(b, m, deterministic)
}
func (dst *ResContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResContent.Merge(dst, src)
}
func (m *ResContent) XXX_Size() int {
	return xxx_messageInfo_ResContent.Size(m)
}
func (m *ResContent) XXX_DiscardUnknown() {
	xxx_messageInfo_ResContent.DiscardUnknown(m)
}

var xxx_messageInfo_ResContent proto.InternalMessageInfo

func (m *ResContent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResContent) GetData() []*Content {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResContent) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func init() {
	proto.RegisterType((*Request)(nil), "grpc.Request")
	proto.RegisterType((*Book)(nil), "grpc.Book")
	proto.RegisterType((*Detail)(nil), "grpc.Detail")
	proto.RegisterType((*Chapter)(nil), "grpc.Chapter")
	proto.RegisterType((*Content)(nil), "grpc.Content")
	proto.RegisterType((*Res)(nil), "grpc.Res")
	proto.RegisterType((*ResChapter)(nil), "grpc.ResChapter")
	proto.RegisterType((*ResContent)(nil), "grpc.ResContent")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BrowserClient is the client API for Browser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrowserClient interface {
	Book(ctx context.Context, opts ...grpc.CallOption) (Browser_BookClient, error)
	Chapter(ctx context.Context, opts ...grpc.CallOption) (Browser_ChapterClient, error)
	Content(ctx context.Context, opts ...grpc.CallOption) (Browser_ContentClient, error)
}

type browserClient struct {
	cc *grpc.ClientConn
}

func NewBrowserClient(cc *grpc.ClientConn) BrowserClient {
	return &browserClient{cc}
}

func (c *browserClient) Book(ctx context.Context, opts ...grpc.CallOption) (Browser_BookClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Browser_serviceDesc.Streams[0], "/grpc.browser/Book", opts...)
	if err != nil {
		return nil, err
	}
	x := &browserBookClient{stream}
	return x, nil
}

type Browser_BookClient interface {
	Send(*Request) error
	Recv() (*Res, error)
	grpc.ClientStream
}

type browserBookClient struct {
	grpc.ClientStream
}

func (x *browserBookClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *browserBookClient) Recv() (*Res, error) {
	m := new(Res)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *browserClient) Chapter(ctx context.Context, opts ...grpc.CallOption) (Browser_ChapterClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Browser_serviceDesc.Streams[1], "/grpc.browser/Chapter", opts...)
	if err != nil {
		return nil, err
	}
	x := &browserChapterClient{stream}
	return x, nil
}

type Browser_ChapterClient interface {
	Send(*Request) error
	Recv() (*ResChapter, error)
	grpc.ClientStream
}

type browserChapterClient struct {
	grpc.ClientStream
}

func (x *browserChapterClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *browserChapterClient) Recv() (*ResChapter, error) {
	m := new(ResChapter)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *browserClient) Content(ctx context.Context, opts ...grpc.CallOption) (Browser_ContentClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Browser_serviceDesc.Streams[2], "/grpc.browser/Content", opts...)
	if err != nil {
		return nil, err
	}
	x := &browserContentClient{stream}
	return x, nil
}

type Browser_ContentClient interface {
	Send(*Request) error
	Recv() (*ResContent, error)
	grpc.ClientStream
}

type browserContentClient struct {
	grpc.ClientStream
}

func (x *browserContentClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *browserContentClient) Recv() (*ResContent, error) {
	m := new(ResContent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BrowserServer is the server API for Browser service.
type BrowserServer interface {
	Book(Browser_BookServer) error
	Chapter(Browser_ChapterServer) error
	Content(Browser_ContentServer) error
}

func RegisterBrowserServer(s *grpc.Server, srv BrowserServer) {
	s.RegisterService(&_Browser_serviceDesc, srv)
}

func _Browser_Book_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrowserServer).Book(&browserBookServer{stream})
}

type Browser_BookServer interface {
	Send(*Res) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type browserBookServer struct {
	grpc.ServerStream
}

func (x *browserBookServer) Send(m *Res) error {
	return x.ServerStream.SendMsg(m)
}

func (x *browserBookServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Browser_Chapter_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrowserServer).Chapter(&browserChapterServer{stream})
}

type Browser_ChapterServer interface {
	Send(*ResChapter) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type browserChapterServer struct {
	grpc.ServerStream
}

func (x *browserChapterServer) Send(m *ResChapter) error {
	return x.ServerStream.SendMsg(m)
}

func (x *browserChapterServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Browser_Content_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrowserServer).Content(&browserContentServer{stream})
}

type Browser_ContentServer interface {
	Send(*ResContent) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type browserContentServer struct {
	grpc.ServerStream
}

func (x *browserContentServer) Send(m *ResContent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *browserContentServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Browser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.browser",
	HandlerType: (*BrowserServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Book",
			Handler:       _Browser_Book_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Chapter",
			Handler:       _Browser_Chapter_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Content",
			Handler:       _Browser_Content_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc/drive.proto",
}

func init() { proto.RegisterFile("grpc/drive.proto", fileDescriptor_drive_bb4c53071af39e65) }

var fileDescriptor_drive_bb4c53071af39e65 = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x66, 0xed, 0x8d, 0x4d, 0x27, 0x6d, 0x15, 0x8d, 0x44, 0xb1, 0x38, 0x40, 0x6b, 0x10, 0xca,
	0x29, 0x54, 0xe9, 0x1b, 0x50, 0x40, 0x42, 0x20, 0x0e, 0x46, 0x9c, 0x23, 0x37, 0x9e, 0xba, 0x2b,
	0x12, 0x6f, 0xd8, 0x5d, 0xf3, 0xf3, 0x20, 0xbc, 0x0d, 0x07, 0x1e, 0x0d, 0xed, 0x8f, 0x1d, 0x9a,
	0x18, 0xa1, 0xde, 0x66, 0x26, 0xdf, 0x37, 0xdf, 0xcc, 0x97, 0x59, 0xc3, 0xa4, 0x56, 0x9b, 0xe5,
	0x8b, 0x4a, 0x89, 0xaf, 0x34, 0xdb, 0x28, 0x69, 0x24, 0x72, 0x5b, 0xc9, 0xdf, 0x43, 0x5a, 0xd0,
	0x97, 0x96, 0xb4, 0xc1, 0x63, 0x88, 0x44, 0x95, 0xc5, 0xa7, 0x6c, 0x7a, 0x50, 0x44, 0xa2, 0xc2,
	0x09, 0xc4, 0xad, 0x5a, 0x65, 0xcc, 0x15, 0x6c, 0x88, 0x4f, 0x60, 0xbc, 0x94, 0xcd, 0xb5, 0xa8,
	0x17, 0x4d, 0xb9, 0xa6, 0x2c, 0x72, 0xbf, 0x80, 0x2f, 0x7d, 0x28, 0xd7, 0x94, 0xff, 0x62, 0xc0,
	0x5f, 0x4a, 0xf9, 0x19, 0x11, 0xb8, 0x29, 0x6b, 0x1d, 0xc8, 0x2e, 0xc6, 0x13, 0x48, 0x2a, 0x32,
	0xa5, 0x58, 0x05, 0x62, 0xc8, 0xf0, 0x29, 0x1c, 0x29, 0xd2, 0xb2, 0x55, 0x4b, 0xf2, 0x7d, 0xfd,
	0x08, 0x87, 0x5d, 0xd1, 0x76, 0xc6, 0x33, 0xe8, 0xf3, 0x85, 0x9d, 0x8a, 0x3b, 0xcc, 0xb8, 0xab,
	0x7d, 0x52, 0x2b, 0x9c, 0xc2, 0xa4, 0x87, 0x88, 0x75, 0xed, 0x60, 0x23, 0x07, 0x3b, 0xee, 0xea,
	0x6f, 0xd7, 0xb5, 0x45, 0x9e, 0x40, 0x52, 0xb6, 0xe6, 0x46, 0xaa, 0x2c, 0xf1, 0x93, 0xf8, 0x2c,
	0x7f, 0x07, 0xc9, 0x2b, 0x3f, 0xd3, 0x5d, 0xe6, 0x7f, 0x00, 0x89, 0xd0, 0x0b, 0x6a, 0x3a, 0xef,
	0x46, 0x42, 0xbf, 0x6e, 0xaa, 0xfc, 0x37, 0x83, 0xf4, 0xf2, 0xa6, 0xdc, 0x18, 0x52, 0xf8, 0x10,
	0x52, 0xa1, 0x17, 0xd7, 0x8a, 0x28, 0x74, 0x4c, 0x84, 0x7e, 0xa3, 0x88, 0xf6, 0x77, 0x8f, 0x06,
	0x76, 0xdf, 0x0a, 0x8f, 0x6e, 0x09, 0xef, 0x7a, 0x12, 0xef, 0x7b, 0x82, 0xc0, 0xb5, 0x54, 0x26,
	0xec, 0xe9, 0xe2, 0x41, 0x9f, 0xf8, 0x90, 0x4f, 0xf9, 0x05, 0xa4, 0x97, 0xb2, 0x31, 0xd4, 0x0c,
	0x93, 0xd8, 0x20, 0x49, 0x42, 0x5c, 0x90, 0x0e, 0xd7, 0xc4, 0xfb, 0x6b, 0x7a, 0x0c, 0xbc, 0x2a,
	0x4d, 0x99, 0xb1, 0xd3, 0x78, 0x3a, 0x9e, 0xc3, 0xcc, 0x5e, 0xdf, 0xcc, 0xde, 0x4a, 0xe1, 0xea,
	0xf8, 0xac, 0x5f, 0xd2, 0xae, 0x31, 0x9e, 0x1f, 0x7a, 0x84, 0xff, 0x3f, 0xfa, 0x95, 0x11, 0x78,
	0x43, 0xdf, 0x8d, 0xb3, 0xe9, 0x7e, 0xe1, 0xe2, 0xfc, 0x07, 0x40, 0x41, 0xba, 0xb3, 0x7a, 0xf7,
	0x8a, 0xcf, 0x6e, 0xe9, 0x1e, 0xf9, 0xae, 0x01, 0xbc, 0x27, 0xcd, 0xef, 0x28, 0xfd, 0xd1, 0x4b,
	0x07, 0x8f, 0xbc, 0x74, 0xf4, 0x1f, 0x69, 0x0f, 0x0e, 0xd2, 0x5d, 0xd3, 0x78, 0xdb, 0x74, 0xfe,
	0x93, 0x41, 0x7a, 0xa5, 0xe4, 0x37, 0x4d, 0x0a, 0x9f, 0x87, 0xf7, 0x14, 0xc8, 0xe1, 0xa9, 0x3e,
	0x3a, 0xe8, 0x52, 0x9d, 0xdf, 0x9b, 0xb2, 0x73, 0x86, 0xe7, 0xdb, 0x5b, 0xdb, 0x81, 0x4e, 0x7a,
	0x68, 0x00, 0xfc, 0xc5, 0x08, 0x73, 0xff, 0x9b, 0xe1, 0x01, 0x9e, 0x71, 0x95, 0xb8, 0xef, 0xc6,
	0xc5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xd4, 0x12, 0xe0, 0x4b, 0x04, 0x00, 0x00,
}
